{{- if (index .Values "postgres-operator" "enabled") -}}
---
{{- range $k, $v := (index .Values "postgres-operator" "postgresqlClusters") }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ $v.name }}
spec:
{{- $v.spec | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}
