{{- if or .Values.certmanager.letsencrypt.enabled .Values.certmanager.zerossl.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 5gzorro-wildcard-cert
spec:
  secretName: 5gzorro-wildcard-cert
  issuerRef: 
    kind: ClusterIssuer
    {{- if .Values.certmanager.zerossl.enabled }}
    name: zerossl-wildcard-prod
    {{- else if .Values.certmanager.letsencrypt.enabled }}
    name: letsencrypt-wildcard-prod
    {{- end }}
  commonName: "*.{{ .Values.certmanager.azureDns.hostedZoneName }}"
  dnsNames:
    - "*.{{ .Values.certmanager.azureDns.hostedZoneName }}"
    - "{{ .Values.certmanager.azureDns.hostedZoneName }}"
{{- end }}