apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - watch
    - patch
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
  - name: argo-workflow
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
---