{{- if and (.Values.strimzi.enabled) (.Values.strimzi.kafkaTopics) -}}
---
{{- range $k, $v := .Values.strimzi.kafkaTopics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $v.name }}
  labels:
    strimzi.io/cluster: {{ $v.clusterName }}
spec:
{{- $v.spec | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}