{{- if (index .Values "certmanager" "zerossl" "enabled") -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-wildcard-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: {{ .Values.certmanager.zerossl.eabKid }}
      keySecretRef:
        name: {{ .Values.certmanager.zerossl.eabHmac.secretName }}
        key: {{ .Values.certmanager.zerossl.eabHmac.secretKey }}
      keyAlgorithm: HS256
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: {{ .Values.certmanager.azureDns.subscriptionID }}
          resourceGroupName: {{ .Values.certmanager.azureDns.resourceGroupName }}
          hostedZoneName: {{ .Values.certmanager.azureDns.hostedZoneName }}
          environment: AzurePublicCloud
          managedIdentity:
            clientID: {{ .Values.certmanager.azureDns.clientID }}
{{- end -}}