{{- if not .Values.postgres.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-data-aggregator-db-credentials
  labels:
{{- include "monitoring-data-aggregator.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  name: {{ .Values.postgres.name | b64enc | quote }}
{{- end }}