apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: issm-api
  namespace: {{ .Chart.Name }}
rules:
- apiGroups:
  - "argoproj.io"
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
  - update