{{- if ne .Values.role "admin" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: issm-argo
  namespace: {{ .Chart.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - pods/exec
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
{{- end -}}