{{- if ne .Values.role "admin" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "issm.fullname" . }}-optimizer
  labels:
    {{- include "issm.labels" . | nindent 4 }}
    issm/component: "optimizer"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "issm.selectorLabels" . | nindent 4 }}
    issm/component: "optimizer"
{{- end }}