{{- if eq .Values.role "admin" }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "issm.serviceAccountName" . }}-optimizer
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "issm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}