include:
  - template: Security/SAST-IaC.latest.gitlab-ci.yml

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup

image: 
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/terraform:1.2.6

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_STATE_NAME: 5gzorro

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

fmt:
  stage: validate
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform fmt -check
  allow_failure: true

validate:
  stage: validate
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform validate

build:
  stage: build
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  resource_group: ${TF_STATE_NAME}
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

deploy:
  stage: deploy
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform apply -auto-approve
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: $DEPLOY == "true"

destroy:
  stage: cleanup
  script:
    - cd "${TF_ROOT}"
    - gitlab-terraform destroy -auto-approve
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: $DESTROY == "true"
