stages:
  - destroy

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

destroy:
  stage: destroy
  script:
    - cd terraform
    - terraform destroy -var-file=testing.tfvars -auto-approve
  rules:
    - if: $DESTROY == "true"


