{{- if .Values.persistence.enabled -}}
{{- $fullName := include "aries-cloudagent.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
spec:
  {{- if .Values.persistence.storageClassName -}}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }}