{{- $fullName := include "aries-cloudagent.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- include "aries-cloudagent.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-agent-seed
type: Opaque
data:
  seed: {{ .Values.agent.seed | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- include "aries-cloudagent.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-agent-did
type: Opaque
data:
  did: {{ .Values.agent.did | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- include "aries-cloudagent.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-walley-key
type: Opaque
data:
  key: {{ .Values.agent.walletKey | b64enc }}