image:
  tag: gitlab-ci
  namespace: domain-operator-a
  app: elma
  image: ghcr.io/5gzorro/elicensing-manager-agent/elma
  pullPolicy: Always
  pullSecrets: elmaregsecret

elmarest:
  nodePort: 30880

elmadb:
  nodePort: 30881

rabbitmq:
  nodePort: 30882
