apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-and-permissions-manager.fullname" . }}
  labels:
    {{- include "identity-and-permissions-manager.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "identity-and-permissions-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "identity-and-permissions-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "identity-and-permissions-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn"]
          args: [{{ if (eq .Values.idp.role "admin")  }}"app.main_admin:app",{{ else if (eq .Values.idp.role "trader") }}"app.main_trading_provider:app",{{ else if (eq .Values.idp.role "regulator") }}"app.main_regulator:app",{{ end }} "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000", "--log-level", "error"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.connectionString }}
                  key: "connectionString.standard"
                  optional: false
            {{- if (eq .Values.idp.role "admin")  }}
            - name: ADMIN_DID
              valueFrom:
                secretKeyRef:
                  name: {{ include "identity-and-permissions-manager.fullname" . }}-did
                  key: "did"
                  optional: false
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "identity-and-permissions-manager.fullname" . }}
          {{- if .Values.livenessProbe }}    
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}  
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe }}  
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
