{{- if (eq .Values.idp.role "admin")  }}
{{- $fullName := include "identity-and-permissions-manager.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- include "identity-and-permissions-manager.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}-did
type: Opaque
data:
  did: {{ .Values.idp.adminDid | b64enc }}
---
{{- end }}