---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stakeholder-registration-{{ .Values.idp.role }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "identity-and-permissions-manager.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "identity-and-permissions-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stakeholder-registration-{{ .Values.idp.role }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "identity-and-permissions-manager.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "identity-and-permissions-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stakeholder-registration-{{ .Values.idp.role }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "identity-and-permissions-manager.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "identity-and-permissions-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stakeholder-registration-{{ .Values.idp.role }}
subjects:
  - name: stakeholder-registration-{{ .Values.idp.role }}
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: Job
metadata:
  name: idp-{{ .Values.idp.role }}-did-registration
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "3"
  labels:
    app.kubernetes.io/name: {{ include "identity-and-permissions-manager.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "identity-and-permissions-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: stakeholder-registration
      labels:
        app.kubernetes.io/name: {{ include "identity-and-permissions-manager.name" . }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "identity-and-permissions-manager.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: stakeholder-registration-{{ .Values.idp.role }}
      initContainers:
      - name: wait-for-aries-cloudagent
        image: "gitlab-registry.fbk.eu/kubernetes-deploy/5g-zorro/misc-tools"
        args:
          - /bin/sh
          - -c
          - >
            set -x;
            while [ $(curl -sw '%{http_code}' "http://{{ .Release.Name }}-aries-cloudagent-{{ .Values.idp.role }}:8001/api/doc" -o /dev/null) -ne 200 ]; do
              sleep 15;
            done
      containers:
        - name: create-did
          image: "gitlab-registry.fbk.eu/kubernetes-deploy/5g-zorro/misc-tools"
          command: ["/bin/sh"]
          args: ["-c", "kubectl create secret generic {{ .Values.idp.role }}-identity-did --from-literal=did=$(curl -X POST -s http://{{ .Release.Name }}-aries-cloudagent-{{ .Values.idp.role }}:8001/wallet/did/create | jq -r .result.did)"]
      restartPolicy: OnFailure