apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rapp-api.fullname" . }}-mongodb
  labels:
    {{- include "rapp-api.labels" . | nindent 4 }}
    rapp-api/component: "mongodb"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rapp-api.selectorLabels" . | nindent 6 }}
      rapp-api/component: "mongodb"
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rapp-api.selectorLabels" . | nindent 8 }}
        rapp-api/component: "mongodb"
    spec:
      containers:
        - image: mongo:3.6
          name: rapp-api-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: data-mongo
            - mountPath: /var/log/mongodb
              name: mongodb-hostpath1
      restartPolicy: Always
      volumes:
        - emptyDir:
            sizeLimit: 500Mi
          name: data-mongo
        - emptyDir:
            sizeLimit: 500Mi
          name: mongodb-hostpath1