apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapp-api.fullname" . }}-mongodb
  labels:
    {{- include "rapp-api.labels" . | nindent 4 }}
    rapp-api/component: "mongodb"
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    {{- include "rapp-api.selectorLabels" . | nindent 4 }}
    rapp-api/component: "mongodb"