apiVersion: v1
kind: Service
metadata:
  name: {{ include "trmf.fullname" . }}
  labels:
    {{- include "trmf.labels" . | nindent 4 }}
    trmf/component: trmf
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trmf.selectorLabels" . | nindent 4 }}
    trmf/component: trmf
