apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trmf.fullname" . }}-mongodb
  labels:
    {{- include "trmf.labels" . | nindent 4 }}
    trmf/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "trmf.selectorLabels" . | nindent 6 }}
      trmf/component: mongodb
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trmf.selectorLabels" . | nindent 8 }}
        trmf/component: mongodb
    spec:
      containers:
        - image: mongo:latest
          name: mongodb-{{ include "trmf.fullname" . }}
          ports:
            - containerPort: 27017
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 5gzorro
          volumeMounts:
            - mountPath: /data/db-{{ include "trmf.fullname" . }}
              name: trust-mongodbdata-{{ include "trmf.fullname" . }}
      restartPolicy: Always
      volumes:
        - name: trust-mongodbdata-{{ include "trmf.fullname" . }}
          persistentVolumeClaim:
            claimName: trust-mongodbdata-{{ include "trmf.fullname" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    {{- include "trmf.selectorLabels" . | nindent 4 }}
  name: trust-mongodbdata-{{ include "trmf.fullname" . }}
spec:
  storageClassName: {{ .Values.trmfdb.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trmfdb.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trmf.fullname" . }}-mongodb
spec:
  selector:
    {{- include "trmf.selectorLabels" . | nindent 4 }}
    trmf/component: mongodb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: trmfdb-mongo-{{ include "trmf.fullname" . }}
