apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "governance-manager-api.fullname" . }}
  labels:
    {{- include "governance-manager-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "governance-manager-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "governance-manager-api.fullname" . }}
        {{- include "governance-manager-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "governance-manager-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "docker.pkg.github.com/5gzorro/governance-manager/governance-manager-api:{{ .Values.dockerTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
        # [SQL Configuration]
        - name: POSTGRES_DB_HOST
          value: {{ .Values.postgres.host }}
        - name: POSTGRES_DB_PORT
          value: "{{ .Values.postgres.port }}"
        - name: IDENTITY_BASE_URL
          value: {{ .Values.identityBaseUrl }}
        - name: LEGAL_PROSE_REPO_BASE_URL
          value: {{ .Values.legalProseRepositoryBaseUrl }}
        - name: UPDATE_PROPOSAL_CALLBACK_URL
          value: {{ .Values.callbacks.updateProposal }}
        - name: POSTGRES_DB_USER
          valueFrom:
              secretKeyRef:
              {{- if .Values.postgres.existingSecret -}}
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postgres.userKey }}
              {{- else }}
                  name: governance-mgr-db-credentials
                  key: username
              {{- end }}
        - name: POSTGRES_DB_PASSWORD
          valueFrom:
              secretKeyRef:
              {{- if .Values.postgres.existingSecret -}}
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postgres.passwordKey }}
              {{- else }}
                  name: governance-mgr-db-credentials
                  key: password
              {{- end }}
        - name: POSTGRES_DB_NAME
          {{- if .Values.postgres.existingSecret -}}
            value: {{ .Values.postgres.name }}
          {{- else }}
          valueFrom:
              secretKeyRef:
                  name: governance-mgr-db-credentials
                  key: name
          {{- end }}
        # [Application Environment Variables]
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.spring.profiles }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.appPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold:  {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.appPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold:  {{ .Values.livenessProbe.failureThreshold }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
