kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "xrm.fullname" . }}-catalogueapp
  labels:
    {{- include "xrm.labels" . | nindent 4 }}
    xrm/component: "catalogueapp"
data:
  mano.json: | {{- tpl (.Files.Get "confs/mano.json") $ | nindent 4 }}
  publicCatalogue.json: | {{- tpl (.Files.Get "confs/publicCatalogue.json") $ | nindent 4 }}