kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "xrm.fullname" . }}-catalogueui
  labels:
    {{- include "xrm.labels" . | nindent 4 }}
    xrm/component: "catalogueui"
data:
  utils.js: | {{- tpl (.Files.Get "confs/utils.js") $ | nindent 4 }}
