apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrm.fullname" . }}-portal-ui
  labels:
    {{- include "xrm.labels" . | nindent 4 }}
    xrm/component: "portal-ui"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xrm.selectorLabels" . | nindent 6 }}
      xrm/component: "portal-ui"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xrm.selectorLabels" . | nindent 8 }}
        xrm/component: "portal-ui"
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xrm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-portal-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.portalui.image.repository }}:{{ .Values.portalui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.portalui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORTAL_API_URL
              value: http://{{ include "xrm.fullname" . }}-management-api:{{ .Values.managementapi.service.port }}/portal/organizations/DEFAULT/environments/DEFAULT/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
