- name: install-von-network
  hosts: all
  vars:
    docker_users:
      - zorro
    docker_install_compose_plugin: true
    docker_packages_state: present

  roles:
    - role: geerlingguy.docker
      become: true

  tasks:
  - name: Checkout Von git repository
    ansible.builtin.git:
      repo: https://github.com/bcgov/von-network.git
      dest: /home/zorro/von-network

  - name: Build VON-Network
    command: "./manage build"
    args:
      chdir: "/home/zorro/von-network"
    register: result

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: result
      verbosity: 2

  - name: Run VON-Network
    command: "./manage start"
    args:
      chdir: "/home/zorro/von-network"
    register: result

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: result
      verbosity: 2