apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srd-api.fullname" . }}
  labels:
    {{- include "srd-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "srd-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "srd-api.fullname" . }}
        {{- include "srd-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "srd-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 5000
            protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.uri }}
                  key: "connectionString.standard"
                  optional: false
        resources:
{{ toYaml .Values.resources | indent 10 }}
