FROM ubuntu:20.04
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
RUN apt update && apt install wget sudo snapd iproute2 -y
RUN wget https://osm-download.etsi.org/ftp/osm-10.0-ten/install_osm.sh
RUN chmod +x install_osm.sh
RUN ./install_osm.sh --charmed --k8s /etc/kube/config