{{- $imageValues := .Values.image }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elma.fullname" . }}
data:
  RABBITMQ_URL: {{ .Values.rabbitmq.url }}
  RABBITMQ_PORT: "5672"
  RABBITMQ_PREFETCH_COUNT: "20"
  RABBITMQ_V_HOST: "/"
  LOG_LEVEL: "DEBUG"
  DRY_RUN: "False"
  MANO: "OSM"
  MANO_VERSION: "ZORRO"
  MANO_TZ: "Europe/Madrid"
  OSM_URL: "ng-ui.osm.svc.cluster.local"
  OSM_PORT: "80"
  DOMAIN_ID: {{ .Values.domainId }}
  ELMA_REST_URL: {{ include "elma.fullname" . }}
  ELMA_REST_PORT: "8000"
  ELMA_REST_URL_1: "172.28.3.15"
  ELMA_REST_PORT_1: "31880"
  ELMA_DB_URL: {{ include "elma.fullname" . }}-mongodb
  ELMA_DB_PORT: "27017"
  DB_RESTART: "False"
  ME_CONFIG_MONGODB_URL: "mongodb://{{ include "elma.fullname" . }}-mongodb:27017/"
  CATALOG_URL: {{ .Values.catalog.url }}
  CATALOG_PORT: {{ .Values.catalog.port | quote }}
  CATALOG_RESOURCES: {{ .Values.catalog.resources }}
  NET_SLICE_ORCHESTRATOR_URL: {{ .Values.netSlice.url | quote }}
  NET_SLICE_ORCHESTRATOR_PORT: {{ .Values.netSlice.port | quote }}
  NET_SLICE_ORCHESTRATOR_ENDPOINT: {{ .Values.netSlice.endpoint }}
  ELMA_RESPONSE_TIMEOUT: "30"
  DATA_LAKE_URL: {{ .Values.datalake.url | quote }}
  DATA_LAKE_AUTH: {{ .Values.datalake.auth | quote }}
  DATA_LAKE_KAFKA: {{ .Values.datalake.kafka }}
