{{- $imageValues := .Values.image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elma.fullname" . }}-watcher
  labels:
    {{- include "elma.labels" . | nindent 4 }}
    elma/component: watcher
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/deployment-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "elma.selectorLabels" . | nindent 6 }}
      elma/component: watcher
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elma.selectorLabels" . | nindent 8 }}
        elma/component: watcher
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: {{ include "elma.fullname" . }}
          - secretRef:
              name: {{ include "elma.fullname" . }}
          env:
            - name: RABBITMQ_USER
              valueFrom:
                  secretKeyRef:
                  {{- if .Values.rabbitmq.existingSecret }}
                    name: {{ .Values.rabbitmq.existingSecret }}
                    key: {{ .Values.rabbitmq.userKey }}
                  {{- else }}
                      name: rabbitmq-elma-default-user
                      key: username
                  {{- end }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                  secretKeyRef:
                  {{- if .Values.rabbitmq.existingSecret }}
                    name: {{ .Values.rabbitmq.existingSecret }}
                    key: {{ .Values.rabbitmq.passwordKey }}
                  {{- else }}
                      name: rabbitmq-elma-default-user
                      key: password
                  {{- end }}
          image: {{ $imageValues.image }}:{{ $imageValues.tag }}
          command: ["watcher_manager", "start", "--frequency", "10"]
          imagePullPolicy: "{{ $imageValues.pullPolicy }}"
          name: elma-watcher-manager
          resources: {}
      {{- if $imageValues.pullSecrets }}
      imagePullSecrets:
        - name: {{ $imageValues.pullSecrets }}
      {{- end }}
      restartPolicy: Always

