{{- if (index .Values "community-operator" "enabled") -}}
---
{{- range $k, $v := (index .Values "community-operator" "mongodbClusters") }}
  {{- range .users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .passwordSecretRef.name }}
type: Opaque
stringData:
  password: {{ randAlphaNum 15| quote }}
---
  {{- end }}
{{- end }}
{{- end }}