{{- $imageValues := .Values.image }}
{{- $elmadb := .Values.elmadb }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elmadb
  namespace: "{{ $imageValues.namespace }}"
  labels:
    app: "{{ $imageValues.app }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elmadb
  template:
    metadata:
      labels:
        app: elmadb
    spec:
      containers:
        - image: mongo:latest
          name: elmadb
          ports:
            - containerPort: 27017
          imagePullPolicy: IfNotPresent
          resources: {}
        - envFrom:
            - configMapRef:
                name: elma-deployment-configmap
          image: mongo-express
          name: mongo-express
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: elmadb-service
  namespace: "{{ $imageValues.namespace }}"
spec:
  selector:
    app: elmadb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: elmadb-mongo
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: {{ $elmadb.nodePort }}
      name: elmadb-express
