{{- $imageValues := .Values.image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elma-watcher-manager
  namespace: "{{ $imageValues.namespace }}"
  labels:
    app: "{{ $imageValues.app }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher-manager
  template:
    metadata:
      labels:
        app: watcher-manager
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: elma-deployment-configmap
          - secretRef:
              name: elma-deployment-secret
          image: {{ $imageValues.image }}:{{ $imageValues.tag }}
          command: ["watcher_manager", "start", "--frequency", "10"]
          imagePullPolicy: "{{ $imageValues.pullPolicy }}"
          name: elma-watcher-manager
          resources: {}
      {{- if $imageValues.pullSecrets }}
      imagePullSecrets:
        - name: {{ $imageValues.pullSecrets }}
      {{- end }}
      restartPolicy: Always

