apiVersion: v2
name: platform-5gzorro
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: community-operator
    version: "0.7.5"
    repository: https://mongodb.github.io/helm-charts
    condition: community-operator.enabled
    tags:
      - base
  - name: custom-resource-5gzorro
    version: "0.1.0"
    condition: custom-resource-5gzorro.enabled
    tags:
      - base
  - name: external-dns
    version: "6.7.*"
    repository: https://charts.bitnami.com/bitnami
    condition: external-dns.enabled
    tags:
      - base
  - name: vault
    version: "0.18.0"
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
    tags:
      - base
  - name: "loki-stack"
    version: "2.6.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
    tags:
      - monitoring
  - name: kube-prometheus-stack
    version: "36.0.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
    tags:
      - monitoring
  - name: minio
    version: "4.0.*"
    repository: https://charts.min.io/
    condition: minio.enabled
    tags:
      - base
  - name: postgres-operator
    version: "1.8.*"
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    condition: postgresOperator.enabled
    tags:
      - base
  - name: strimzi-kafka-operator
    version: "0.29.*"
    repository: https://strimzi.io/charts/
    condition: strimzi.enabled
    tags:
      - base
  - name: redis
    version: "16.13.*"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - base
  - name: argo-workflows
    version: "0.16.*"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-workflows.enabled
    tags:
      - base
  - name: elma
    alias: elma-agent
    version: "3.1.*"
    tags:
      - trader
    condition: elma-agent.enabled
  - name: elma
    alias: elma-core
    version: "3.1.*"
    tags:
      - base
    condition: elma-core.enabled
  - name: monitoring-data-aggregator
    version: "0.1.*"
    condition: monitoring-data-aggregator.enabled
    tags:
      - admin
      - treder
      - regulator
###### Da verificare profili #######      
  - name: aries-cloudagent
    alias: aries-cloudagent-admin
    version: "0.1.*"
    condition: aries-cloudagent-admin.enabled
    tags:
      - admin
      - aries
  - name: aries-cloudagent
    alias: aries-cloudagent-regulator
    version: "0.1.*"
    condition: aries-cloudagent-regulator.enabled
    tags:
      - regulator
      - aries
  - name: aries-cloudagent
    alias: aries-cloudagent-holder
    version: "0.1.*"
    condition: aries-cloudagent-holder.enabled
    tags:
      - trader
      - aries
  - name: aries-cloudagent
    alias: aries-cloudagent-verifier
    version: "0.1.*"
    condition: aries-cloudagent-verifier.enabled
    tags:
      - consumer
      - aries
###### Da verificare profili #######   
  - name: identity-and-permissions-manager
    alias: identity-and-permissions-manager-admin
    version: "0.1.*"
    condition: identity-and-permissions-manager-admin.enabled
    tags:
      - admin
      - idp
  - name: identity-and-permissions-manager
    alias: identity-and-permissions-manager-trader
    version: "0.1.*"
    condition: identity-and-permissions-manager-trader.enabled
    tags:
      - trader
      - idp
  - name: identity-and-permissions-manager
    alias: identity-and-permissions-manager-consumer
    version: "0.1.*"
    condition: identity-and-permissions-manager-consumer.enabled
    tags:
      - consumer
      - idp
  - name: identity-and-permissions-manager
    alias: identity-and-permissions-manager-regulator
    version: "0.1.*"
    condition: identity-and-permissions-manager-regulator.enabled
    tags:
      - regulator
      - idp
  - name: governance-manager-api
    alias: governance-manager-api-admin
    version: "0.1.*"
    condition: governance-manager-api-admin.enabled
    tags:
      - admin
  - name: governance-manager-api
    alias: governance-manager-api-regulator
    version: "0.1.*"
    condition: governance-manager-api-regulator.enabled
    tags:
      - regulator
  - name: legal-prose-repository
    alias: legal-prose-repository-admin
    version: "0.1.*"
    condition: legal-prose-repository-admin.enabled
    tags:
      - admin
  - name: legal-prose-repository
    alias: legal-prose-repository-regulator
    version: "0.1.*"
    condition: legal-prose-repository-regulator.enabled
    tags:
      - regulator
  - name: smart-contract-lifecycle-manager
    alias: smart-contract-lifecycle-manager-admin
    version: "0.1.*"
    condition: smart-contract-lifecycle-manager-admin.enabled
    tags:
      - admin
      - trader
      - regulator
  - name: smart-contract-lifecycle-manager
    alias: smart-contract-lifecycle-manager-trader
    version: "0.1.*"
    condition: smart-contract-lifecycle-manager-trader.enabled
    tags:
      - admin
      - trader
      - regulator
  - name: smart-contract-lifecycle-manager
    alias: smart-contract-lifecycle-manager-regulator
    version: "0.1.*"
    condition: smart-contract-lifecycle-manager-regulator.enabled
    tags:
      - admin
      - trader
      - regulator
  - name: resource-and-service-offer-catalog
    alias: resource-and-service-offer-catalog-admin
    version: "0.1.*"
    condition: resource-and-service-offer-catalog-admin.enabled
    tags:
      - admin
      - trader
      - regulator