---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stakeholder-registration
  # namespace: {{ include "platform-5gzorro.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stakeholder-registration
  # namespace: {{ include "platform-5gzorro.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stakeholder-registration
  # namespace: {{ include "platform-5gzorro.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stakeholder-registration
subjects:
  - name: stakeholder-registration
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "platform-5gzorro.fullname" . }}-crd-cleanup
  namespace: {{ include "platform-5gzorro.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: stakeholder-registration
      labels:
        app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:

      serviceAccountName: stakeholder-registration
      containers:
        - name: kubectl
          image: "bitnami/kubectl"
          args:
          - delete 
          - crds 
          - -l app.kubernetes.io/name=platform-5gzorro
      restartPolicy: OnFailure