{{- if .Values.global.singleOperator.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ambassador-certs
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "3"
type: Opaque
data:
{{ (.Files.Glob "confs/certs/*").AsSecrets | indent 2 }}
---
{{- end }}