# Delete all resources (mongo and postgress) this prevent terraform destroy to fail
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: ["rabbitmq.com"]
    resources: ["rabbitmqclusters"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["mongodbcommunity.mongodb.com"]
    resources: ["mongodbcommunity"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["acid.zalan.do"]
    resources: ["postgresqls"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets" ]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ['*']
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ['*']
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ['*']
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ['*']
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: delete-resources
subjects:
  - name: delete-resources
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-resources
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: delete-resources
      labels:
        app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: delete-resources
      containers:
        - name: delete-resources
          image: "{{ .Values.global.miscTools.image.repository }}:{{ .Values.global.miscTools.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args: ["-c", "kubectl delete kustomizations,helmcharts,helmreleases,helmrepositories,gitrepositories --all --all-namespaces && kubectl delete --force --grace-period=0 eventbus,eventsources,sensors --all --all-namespaces && kubectl delete postgresql --all && kubectl delete rabbitmqcluster --all && kubectl delete statefulsets.apps --all && sleep 3m"]
      restartPolicy: OnFailure