apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-corda
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3"
  labels:
    app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: deploy-corda
      labels:
        app.kubernetes.io/name: {{ include "platform-5gzorro.name" . }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "platform-5gzorro.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: deploy-corda
          image: ghcr.io/5gzorro/platform-automation/bevel:latest
          command: ["/bin/bash"]
          args: ["run.sh"]
          volumeMounts:
            - name: corda-config
              mountPath: /home/build/network.yaml
              subPath: network.yaml
            - name: kube-config
              mountPath: /home/build/config
              subPath: config
      volumes:
        - name: corda-config
          configMap:
            name: corda-network
            items:
              - key: network.yaml
                path: network.yaml
        - name: kube-config
          secret:
            secretName: kubeconfig
      restartPolicy: Never