defaultRules:
  etcd: false
  kubeScheduler: false

grafana:
  defaultDashboardsTimezone: Europe/Rome
  adminPassword: 5gzorro-metrics

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 180d
    retentionSize: "30GB"
    storageSpec:
      volumeClaimTemplate:
       spec:
         storageClassName: managed-premium
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 32Gi