kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "sla-breach-predictor.fullname" . }}
  labels:
    {{- include "sla-breach-predictor.labels" . | nindent 4 }}
data:
  properties.conf: | {{- tpl (.Files.Get "confs/properties.conf") $ | nindent 4 }}