apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: file
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /data/
          name: shared-test
    volumes:
      - name: shared-test
        persistentVolumeClaim:
          claimName: isbp-claim
  file:
    predict:
      watchPathConfig:
        # directory to watch
        directory: /data/
        # path to watch
        pathRegexp: (.+)-data.json
      # type of the event
      # supported types are: CREATE, WRITE, REMOVE, RENAME, CHMOD
      eventType: CREATE
    train:
      watchPathConfig:
        # directory to watch
        directory: /data/
        # path to watch
        pathRegexp: (.+)-model.json
      # type of the event
      # supported types are: CREATE, WRITE, REMOVE, RENAME, CHMOD
      eventType: CREATE
      