apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sla-breach-predictor.fullname" . }}-isbp
  labels:
    {{- include "sla-breach-predictor.labels" . | nindent 4 }}
    sla-breach-predictor/component: isbp
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sla-breach-predictor.selectorLabels" . | nindent 6 }}
      sla-breach-predictor/component: isbp
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sla-breach-predictor.selectorLabels" . | nindent 8 }}
        sla-breach-predictor/component: isbp
    spec:
      {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sla-breach-predictor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.isbp.image.repository }}:{{ .Values.isbp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.isbp.image.pullPolicy }}
          command: ["uvicorn", "sla-service:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared-test
              mountPath: /data/
            - name: properties-conf
              mountPath: /isbp/properties.conf
              subPath: properties.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: shared-test
          persistentVolumeClaim:
            claimName: {{ include "sla-breach-predictor.fullname" . }}-pvc
        - name: properties-conf
          configMap:
              name: {{ include "sla-breach-predictor.fullname" . }}
              items:
                - key: properties.conf
                  path: properties.conf