apiVersion: v1
kind: Service
metadata:
  name: isbpminio
  labels:
    {{- include "sla-breach-predictor.labels" . | nindent 4 }}
    sla-breach-predictor/component: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sla-breach-predictor.selectorLabels" . | nindent 4 }}
    sla-breach-predictor/component: minio
