apiVersion: v1
kind: Service
metadata:
  name: {{ include "sla-breach-predictor.fullname" . }}-predictor
  labels:
    {{- include "sla-breach-predictor.labels" . | nindent 4 }}
    sla-breach-predictor/component: predictor
spec:
  type: {{ .Values.predictor.service.type }}
  ports:
    - port: {{ .Values.predictor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sla-breach-predictor.selectorLabels" . | nindent 4 }}
    sla-breach-predictor/component: predictor
