apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-corda
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      imagePullSecrets: 
        - name: "registry-credentials"
      containers:
        - name: baf
          image: gitlab-registry.fbk.eu/kubernetes-deploy/5g-zorro/baf-build:reset-fix
          env:
            - name: GIT_SSH_URI
              value: "https://gitlab.fbk.eu/ffais/blockchain-automation-framework-4.7.git"
            - name: GIT_REPO
              value: "gitlab.fbk.eu/ffais/blockchain-automation-framework-4.7.git"
            - name: GIT_PRIVATE_KEY
              value: "/home/blockchain-automation-framework/build/5gzorro"
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: username
                  optional: false
            - name: GIT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: email
                  optional: false
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: token
                  optional: false
            - name: VAULT_URI
              value: "http://vault.5gzorro.smartcommunitylab.it:8200"
            - name: VAULT_ROOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-creds
                  key: token
                  optional: false
            - name: DOORMAN_URI
              value: "https://doorman.5gzorro.smartcommunitylab.it"
            - name: NETWORK_MAP_URI
              value: "https://networkmap.5gzorro.smartcommunitylab.it"
            - name: EXTERNAL_URL_SUFFIX
              value: "5gzorro.smartcommunitylab.it"
            - name: DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: docker-creds
                  key: username
                  optional: false
            - name: DOCKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docker-creds
                  key: password
                  optional: false
            - name: K8S_CONTEXT
              value: "5gzorro"
          volumeMounts:
              - name: kubeconfig
                mountPath: "/home/blockchain-automation-framework/build/config.ro"
                subPath: "config"
                readOnly: true
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
            optional: false
      restartPolicy: Never
  backoffLimit: 4
