apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rsoc-api.fullname" . }}
  labels:
    {{- include "rsoc-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "rsoc-api.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        app: {{ include "rsoc-api.fullname" . }}
        {{- include "rsoc-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rsoc-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort:  {{ .Values.service.appPort }}
            protocol: TCP
        env:
          - name: OFFER_CATALOG_HOSTNAME
            value: {{ .Values.hostname }}
          - name: SERVER_PORT
            value: {{ .Values.service.appPort | quote }}
          - name: POSTGRES_HOSTNAME
            value: "{{ .Values.postgres.host }}"
          - name: POSTGRES_PORT
            value: "{{ .Values.postgres.port }}"
          - name: POSTGRES_MODE
            value: {{ .Values.postgres.mode }}
          - name: POSTGRES_USER
            valueFrom:
                secretKeyRef:
                {{- if .Values.postgres.existingSecret }}
                    name: {{ .Values.postgres.existingSecret }}
                    key: {{ .Values.postgres.userKey }}
                {{- else }}
                    name: mda-api-db-credentials
                    key: username
                {{- end }}
          - name: POSTGRES_PSW
            valueFrom:
                secretKeyRef:
                {{- if .Values.postgres.existingSecret }}
                    name: {{ .Values.postgres.existingSecret }}
                    key: {{ .Values.postgres.passwordKey }}
                {{- else }}
                    name: mda-api-db-credentials
                    key: password
                {{- end }}
          - name: KAFKA_BOOTSTRAP_ADDRESS
            value: {{ .Values.kafka.bootstrap }} 
          - name: KAFKA_TOPIC_OFFERINGS
            value: "{{ .Values.kafka.offeringsTopic }}"
          - name: KAFKA_TOPIC_ORDERS
            value: "{{ .Values.kafka.ordersTopic }}"
          - name: DID_SERVICE_HOSTNAME
            value: {{ .Values.did.host }}
          - name: DID_SERVICE_PORT
            value: {{ .Values.did.port | quote }}
          - name: DID_SERVICE_REQUEST_PATH
            value: {{ .Values.did.requestPath }}
          - name: SC_LCM_HOSTNAME
            value: {{ .Values.lcm.host }}
          - name: SC_LCM_PORT
            value: {{ .Values.lcm.port | quote }}
          - name: SC_LCM_PRODUCT_OFFER_REQUEST_PATH
            value: {{ .Values.lcm.offerPath }}
          - name: SC_LCM_PRODUCT_ORDER_REQUEST_PATH
            value: {{ .Values.lcm.orderPath }}
          - name: SC_LCM_DERIVATIVE_ISSUE_REQUEST_PATH
            value: {{ .Values.lcm.issuePath }}
          - name: SC_LCM_SLA_REQUEST_PATH
            value: {{ .Values.lcm.slaPath }}
          - name: SKIP_SC_LCM_POST
            value: {{ .Values.lcm.skipPost | quote }}
          - name: SRSD_HOSTNAME
            value: {{ .Values.srsd.host }}
          - name: SRSD_PORT
            value: {{ .Values.srsd.port | quote }}
          - name: SRSD_REQUEST_PATH
            value: {{ .Values.srsd.requestPath }}
          - name: SKIP_SRSD_POST
            value: {{ .Values.srsd.skipPost | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
