apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-operator-dashboard-frontend-config-{{ .Values.role }}
data:
  config.js: | {{- tpl (.Files.Get "environments/env.tpl") $ | nindent 4 -}}