{{- if not .Values.postgres.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: datalake-db-credentials
  labels:
{{- include "datalake.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  name: {{ .Values.postgres.name | b64enc | quote }}
{{- end }}
---
{{- if not .Values.minio.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: datalake-minio-credentials
  labels:
{{- include "datalake.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.minio.username | b64enc | quote }}
  password: {{ .Values.minio.password | b64enc | quote }}
{{- end }}