apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datalake.fullname" . }}
  labels:
    {{- include "datalake.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "datalake.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datalake.selectorLabels" . | nindent 8 }}
    spec:
    {{- with (default .Values.global.imagePullSecrets .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "datalake.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key, $val := .Values.global.imagePullSecrets }}
            - name: IMAGE_PULL_SECRETS
              value: {{ $val.name }}
            {{- end }}
            - name: IMAGE_REPOSITORY
              value: {{ .Values.datalake.imageRepository }}
            - name: DATALAKE_NAMESPACE
              value: {{ .Values.namespace | default .Release.Namespace }}
            - name: KAFKA_URL
              value: {{ .Values.kafka.host }}:{{ .Values.kafka.port }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: DATALAKE_DB_USER
              valueFrom:
                  secretKeyRef:
                  {{- if .Values.postgres.existingSecret }}
                    name: {{ .Values.postgres.existingSecret }}
                    key: {{ .Values.postgres.userKey }}
                  {{- else }}
                      name: datalake-db-credentials
                      key: username
                  {{- end }}
            - name: DATALAKE_DB_USER_PW
              valueFrom:
                  secretKeyRef:
                  {{- if .Values.postgres.existingSecret }}
                    name: {{ .Values.postgres.existingSecret }}
                    key: {{ .Values.postgres.passwordKey }}
                  {{- else }}
                      name: datalake-db-credentials
                      key: password
                  {{- end }}
            - name: DATALAKE_IMAGES_VERSION
              value: {{ .Values.datalake.imageVersion | quote }}
            - name: DATALAKE_DB
              value: {{ .Values.postgres.name }}
            - name: DATALAKE_DB_TABLE
              value: {{ .Values.postgres.table }}
            - name: S3_URL
              value: {{ .Values.minio.host }}
            - name: S3_ACCESS_KEY
              valueFrom:
                  secretKeyRef:
                  {{- if .Values.minio.existingSecret }}
                    name: {{ .Values.minio.existingSecret }}
                    key: {{ .Values.minio.passwordKey }}
                  {{- else }}
                    name: datalake-minio-credentials
                    key: password
                  {{- end }}
            - name: S3_SECRET_KEY
              valueFrom:
                  secretKeyRef:
                  {{- if .Values.minio.existingSecret }}
                    name: {{ .Values.minio.existingSecret }}
                    key: {{ .Values.minio.passwordKey }}
                  {{- else }}
                    name: datalake-minio-credentials
                    key: password
                  {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
