{{- if not .Values.nfvo.lcm.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nsso.fullname" . }}
  labels:
    {{- include "nsso.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.nfvo.lcm.username | b64enc | quote }}
  password: {{ .Values.nfvo.lcm.password | b64enc | quote }}
{{- end }}