{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nsso.serviceAccountName" . }}
  labels:
{{ include "nsso.labels" . | nindent 4 }}
{{- end -}}
