apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsso.fullname" . }}-ui
  labels:
    {{- include "nsso.labels" . | nindent 4 }}
    nsso/component: "nsso-ui"
spec:
  type: {{ .Values.uiservice.type }}
  ports:
    - port: {{ .Values.uiservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nsso.labels" . | nindent 4 }}
    nsso/component: "nsso-ui"
