apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-contract-lifecycle-mgr-api.fullname" . }}-corda-credentials
  labels:
{{- include "smart-contract-lifecycle-mgr-api.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.corda.username | b64enc }}
  password: {{ .Values.corda.password | b64enc }}