{{- if not .Values.postgres.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: smart-contract-lifecycle-mgr-api-db-credentials
  labels:
{{- include "smart-contract-lifecycle-mgr-api.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  name: {{ .Values.postgres.name | b64enc }}
{{- end }}